### PR TITLE
Add support for Flex target

### PR DESCRIPTION
**Pull request by jasonxh**
Also refresh/fix functional tests for Stax.

### CODE REVIEW

**Comment by vforgeoux-ledger** [comment]
Hey @jasonxh , can you please update the useCases to the latest ones that are detailed [here](https://developers.ledger.com/docs/device-app/develop/ui/ledger-stax-flex-display) ?

**Comment by jasonxh** [comment]
> Hey @jasonxh , can you please update the useCases to the latest ones that are detailed [here](https://developers.ledger.com/docs/device-app/develop/ui/ledger-stax-flex-display) ?

Finally got around to this. Let me know how it looks @vforgeoux-ledger .

**Comment by vforgeoux-ledger** [comment]
Hey @jasonxh  , I tested it and functionally it looks good to me! 

Can we get a review from someone from Aptos Labs ? 

Then, we can pretty quickly deploy the Aptos app update if a PR is opened against this branch https://github.com/LedgerHQ/app-aptos/tree/develop

**Comment by jasonxh** [comment]
> Then, we can pretty quickly deploy the Aptos app update if a PR is opened against this branch https://github.com/LedgerHQ/app-aptos/tree/develop

Oh I didn't realize there's another repo. Should I close this PR and open a new one over there @vforgeoux-ledger ?

**Comment by vforgeoux-ledger** [comment]
I don't know if Aptos prefer to merge your PR here first (or even [here](https://github.com/pontem-network/ledger-app-aptos) which is the repo we forked), and then open a new one, but indeed in the end we need a PR opened on LedgerHQ otherwise we can't deploy the update.

**Comment by jasonxh** [comment]
Closing this in favor of https://github.com/LedgerHQ/app-aptos/pull/17

**Pull request closed without merging**
